[tool.poetry]
name = "egeria-workspaces"
version = "0.1.0"
description = ""
authors = ["Dan Wolfson <dwolfson@users.noreply.github.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
jupyter = "^1.0.0"
rich = "^13.7.1"
pyegeria = "^0.5.5.9"
unitycatalog = "^0.1.1"
nest-asyncio = "^1.6.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
