#FROM quay.io/odpi/egeria-platform:latest
FROM docker.io/odpi/egeria-platform:latest@sha256:2f4a80a6406a04aef2f051c3aae0d89531c6701998bed31bcf8f829b46ee8d89
# Quickstart now relies on runtime-mounted /deployments content and default image behavior.

